import {ReactNode} from "react";
import { Inter } from 'next/font/google';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const RootLayout = ({children}: {children: ReactNode }) => {
  return (
    <html lang="pl">
      <body className={inter.className}>{children}</body>
    </html>
  );
};
