import React, { ReactNode } from "react";
// eslint-disable-next-line
import { Bebas_Neue,Oxygen } from "next/font/google";

import { Footer } from "@/components/layout/footer/Footer";
import { Header } from "@/components/layout/header/Header";
import { WindowDimensionsProvider } from "@/context/WindowDimensionsContext";

import "./globals.scss";

const oxygen = Oxygen({
  weight: ["400", "700"],
  display: "swap",
  variable: "--theme-font-body",
  fallback: ["Helvetica", "sans-serif"],
  subsets: ["latin", "latin-ext"],
});

 
const bebas = Bebas_Neue({
  weight: ["400"],
  display: "swap",
  variable: "--theme-font-display",
  fallback: ["cursive"],
  subsets: ["latin", "latin-ext"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <WindowDimensionsProvider>
      <html lang="pl" className={`${oxygen.variable} ${bebas.variable} light`}>
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </WindowDimensionsProvider>
  );
};

export default RootLayout;
